wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
hidden_dim:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1700613112.412078
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.16.0
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
